vim.cmd('colorscheme gruvbox-baby')
require('plugins')
require('lsp')
require('keybindings')
require('options')
require('blankline')
require('icons-config')
require('treesitter-config')
require('lualine-config')
require('autopairs-config')
require('lsputils-config')
require('telescope-config')
require('go-config')
