vim.cmd('colorscheme gruvbox')
require('keybindings')
require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('lsp')
require('lsputils-config')
require('lint-config')
require('telescope-config')
require('go-config')
